modLoader = "javafml"
loaderVersion = "[54,)"
issueTrackerURL = "https://github.com/JT122406/MoreStructureProcessors/issues"
license = "All Rights Reserved"

[[mods]]
modId = "moreprocessors"
version = "${version}"
displayName = "More Structure Processors"
authors = "Joseph T. McQuigg"
description = '''
Adds more structure processors for Developers to use in Mods or Datapacks
'''
logoFile = "icon.png"

[[dependencies.moreprocessors]]
modId = "forge"
mandatory = true
versionRange = "[54,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moreprocessors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.4]"
ordering = "NONE"
side = "BOTH"
